using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projeto_MVC.Models
{
    public class Clinica
    {

        INTEGRAÇÃO
 ,AMA
 ,CIRURGIA PLASTICA 
 ,QUEIMADO ADULTO 
 ,QUEIMADO PEDIATRICO 
 ,NEUROLOGIA 
 ,CENTRO CIRÚRGICO 
, CENTRO OBSTÉTRICO 
, UNIDADE DE TRATAMENTO INTENSIVO 
, UTI ADULTO 
, UTI QUEIMADOS 
, UTI INFANTIL 
, UTI NEONATAL 
, GINECOLOGIA 
, OBSTETRÍCIA CIRÚRGICA 
, OBSTETRÍCIA CLÍNICA 
, PEDIATRIA CIRÚRGICA 
, PEDIATRIA CLÍNICA 
, NEUROCIRURGIA 
, UNIDADE DE CUIDADO INTERMEDIÁRIO NEONATAL 
, CIRURGIA GERAL 
, PSIQUIATRIA 
, CLÍNICA GERAL 
, ORTOPEDIA E TRAUMATOLOGIA 
, OBSTETRÍCIA 
, PEDIATRIA 
, AMBULATÓRIO DE ORTOPEDIA E TRAUMATOLOGIA 
, PRONTO SOCORRO 
, UNIDADE DE CUIDADO INTERMEDIÁRIO 
, AMBULATORIO DE EGRESSOS 
, AMBULATÓRIO DE PSIQUIATRIA 
, AMBULATÓRIO DE NEONATOLOGIA 
, AMBULATORIO QUEIMADOS s
, CIRURGICA PAI 
, MEDICA PAI 
,UNIDADE DE CUIDADO INTERMEDIÁRIO NEONATAL CANGURU 
, UNIDADE DE CUIDADOS INTERMEDIÁRIO PEDIATRICO 
, UNIDADE DE CUIDADOS INTERMEDIARIO ADULTO 
, NEONATOLOGIA 
, HOSPITAL DIA (TRAT. DIAG. E TERAPEUTICO) 
, OBSERVAÇÃO PEDIÁTRICA 
, OBSERVAÇÃO MASCULINO 
, OBSERVAÇÃO 
, OBSERVAÇÃO FEMININO 
, OBSERVAÇÃO INDIFERENCIADA 
, OBSERVAÇÃO PSIQUIÁTRICA 
, CHOQUE 
, BUCO MAXILO FACIAL 
, AMBULATÓRIO 
, ENFERMARIA 10º ANDAR - LEITOS CLÍNICOS 
, ENFERMARIA 6º ANDAR - UTI 6º 
, UTI GERAL 
, ENFERMARIA 7º ANDAR - UTI 7º 
, ENFERMARIA 12º ANDAR 
, ENFERMARIA 11º ANDAR 
, ENFERMARIA  9º ANDAR - UCEE 
, ENFERMARIA  9º ANDAR B  - LEITOS CIRÚRGICOS 
, ENFERMARIA 8º ANDAR - MATERNIDADE 
, ENFERMARIA 8º ANDAR - LEITOS CIRÚRGICO 
, ENFERMARIA 8º ANDAR - BERÇÁRIO C INTERMEDIÁRIO 
, ENFERMARIA 8º ANDAR -  BERÇÁRIO C ESPECIAIS 
, ENFERMARIA 8º ANDAR - UTI NEONATAL 
, ENFERMARIA 8º ANDAR  - PEDIATRIA 
, ENFERMARIA 8º ANDAR - UTI PED - UCE 
, ENFERMARIA 8º ANDAR - UTI PEDIÁTRICA 
, ENFERMARIA 4º ANDAR - LEITOS GERAIS 
, ENFERMARIA 1º ANDAR - PST 
, PSI - PRONTO SOCORRO INFANTIL 
, AMBULATÓRIO TESTE 
, ACUPUNTURA 
, TESTE PSICOLOGIA 
, TERAPIA DE REIKI 
, OTORRINO 
, AMBULATORIO GERAL 
, AMBULATÓRIO CARRÃO 
, AMBULATÓRIO HSPM 
, AMBULATÓRIO LAPA 
, AMBULATÓRIO SANTO AMARO 
, AMBULATÓRIO SÃO MIGUEL 
, AMBULATÓRIO TUCURUVI 
, UNIDADE DE INTERNAÇÃO 
, HOSPITAL DIA  (TRAT CIRURGICO) 
, UNIDADE HOSPITAL DIA 
, CENTRO DE DIAGNÓSTICO POR IMAGEM E TRAÇADOS 
, GUICHÊ PÓS CONSULTA 
, ENFERMARIA 10º ANDAR - UTI 10º 
, ENFERMARIA 1º ANDAR - GRIPARIO 
, ENFERMARIA 9º ANDAR - A -  LEITOS CLINICOS 
, ENFERMARIA DO 11º ANDAR - UTI 11º 
, LABORATÓRIO DE PATOLOGIA CLÍNICA 
, LABORATÓRIO COLETA 

    }
}
